name: dosage-tracker
base: core24
adopt-info: dosage-tracker
grade: stable
confinement: strict

parts:
  dosage-tracker:
    after: [blueprint-compiler]
    plugin: meson
    source: https://github.com/diegopvlk/Dosage.git
    source-depth: 1
    build-environment:
      - GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gjs/girepository-1.0:$GI_TYPELIB_PATH
    meson-parameters:
      - --prefix=/snap/dosage-tracker/current/usr
    build-snaps:
      - blueprint-compiler
    organize:
      snap/dosage-tracker/current: .
    parse-info: [usr/share/appdata/io.github.diegopvlk.Dosage.appdata.xml]
    prime:
      - -snap/dosage-tracker

slots:
  dosage-tracker:
    interface: dbus
    bus: session
    name: io.github.diegopvlk.Dosage

apps:
  dosage-tracker:
    command: usr/bin/io.github.diegopvlk.Dosage
    desktop: usr/share/applications/io.github.diegopvlk.Dosage.desktop
    autostart: dosage-tracker-startup.desktop
    common-id: io.github.diegopvlk.Dosage
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$GI_TYPELIB_PATH
    extensions:
      - gnome
    plugs:
      - audio-playback
      - login-session-observe
