export const dateFormats = {
	// specify format for locale code:
	// en-NG: '%A, %b %-e %Y'
	be: '%A, %-e %b %Y',
	bg: '%A, %-e %b %Y',
	cs: '%A %-e. %b %Y',
	de: '%A, %-e. %b %Y',
	en: '%A, %b %-e, %Y',
	es: '%A, %-e de %b de %Y',
	fa: '%Y %b %-e %A',
	fi: '%A, %-e. %B %Y',
	fr: '%A %-e %b. %Y',
	he: '%A %-e %b %Y',
	hi: '%A, %-e %b %Y',
	it: '%A, %-e %b %Y',
	ko: '%Y년 %-m월 %-e일 %A',
	nb: '%A %-e. %b %Y',
	nl: '%A %-e %b %Y',
	pt: '%A, %-e de %b. de %Y',
	ru: '%A, %-e %b. %Y',
	sv: '%A %-e %b. %Y',
	ta: '%A, %-e %b, %Y',
	tr: '%-e %b %Y %A',
	uk: '%A, %-e %b. %Y',
};
