name: Build Snap
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
permissions:
  id-token: write
  contents: read
jobs:
  deploy-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        with:
          snapcraft-args: "--verbosity debug"
          path: "build-aux"
      - uses: actions/upload-artifact@v4
        with:
          name: dosage-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}
